version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017  # Connect to the MongoDB container
      - DATABASE_NAME=payments_db
    volumes:
      - .:/app

volumes:
  mongodb_data:
